[project]
name = "stratos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.74",
    "langchain-milvus>=0.2.1",
    "langchain-ollama>=0.3.7",
]
